### ISSUE TITLE
Add Navigation

### ISSUE THREAD

**Issue by shadmazumder** [shadmazumder/Ice-and-Fire#10]
By using `react-navigation` we can achieve our navigation for this app. Please refer to [Screen](https://github.com/shadmazumder/Ice-and-Fire/wiki/Requirements) for more details on individual screen of the app.

+ After the splash screen we will have a `TabNavigator` with two Tab-screen, **House** Tab and **Book** Tab.
+ Both the Tab-screen will have a `StackNavigator`, which will make sure we can go to the next screen by tapping any of the entity of the list view of **House** Tab or **Book** Tab. Next screen means **House Details** and **Character List** for **House** Tab and **Book** Tab respectively.
+ Now both the **House Details** and **Character List** have a list of characters, bottom view for **House Details** and whole view for **Character List**. This two screens, **House Details** and **Character List**, also needed to be a `StackNavigator` to move next screen **Character Details** when user taps on a entity or character.

[Similar implementation](https://reactnavigation.org/docs/intro/nesting#Nesting-a-Navigator-in-a-screen)

[Video Tutorial](https://www.youtube.com/watch?v=C96piR3FRww)

**Comment by puzzlemusa** [comment]
Added tab bar.

**Comment by shadmazumder** [comment]
[Merged ](https://github.com/shadmazumder/Ice-and-Fire/pull/30)
