### ISSUE TITLE
Splash Screen or Launch Screen.

### ISSUE THREAD

**Issue by shadmazumder** [shadmazumder/Ice-and-Fire#8]
~Api call and update for next scene.~

Static image.

[How to](https://www.youtube.com/watch?v=rnLR65OGtic)
[Generator](https://apetools.webprofusion.com/)
[Android](https://www.bignerdranch.com/blog/splash-screens-the-right-way/)

**Comment by asaduzzaman-shuvro** [comment]
Add static image to asset file of iOS. for android set image at manufest.

**Comment by shadmazumder** [comment]
[Splash screen generator] (http://zeppelindev.com/splash.html#none), can also be used for generating icons.
Can be [useful](https://medium.com/the-react-native-log/tips-for-react-native-images-or-saying-goodbye-to-trial-and-error-b2baaf0a1a4d)

**Comment by puzzlemusa** [comment]
Added splash screen for android. Not fully working yet.

**Comment by puzzlemusa** [comment]
Fixed the console error.

**Comment by puzzlemusa** [comment]
[pr1](https://github.com/shadmazumder/Ice-and-Fire/pull/46)
[pr2](https://github.com/shadmazumder/Ice-and-Fire/pull/43)
